# Generated by Django 4.1.5 on 2023-01-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.DecimalField(decimal_places=0, max_digits=10)),
                ('username', models.TextField()),
                ('address', models.TextField()),
                ('town', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
    ]
